version: "3.7"
services:
    starbound-server:
        build: .
        image: openmediavault:5000/starbound-dedicated-server
        container_name: starbound-dedicated-server
        ports:
            - "21025:21025"
        volumes:
            - ./data:/starbound
        restart: always