version: "3.7"

services:
  minecraft-vanilla:
    # https://github.com/itzg/docker-minecraft-server
    container_name: minecraft-vanilla
    image: itzg/minecraft-server
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
       - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
       - ENABLE_COMMAND_BLOCK=true
       - EULA=true
       - FORCE_GAMEMODE=true
       - GENERATE_STRUCTURES=true
       - MAX_MEMORY=4G
       - MEMORY=2G
       - RCON_PASSWORD=password
       - TYPE=VANILLA
       - VERSION=LATEST
       - VIEW_DISTANCE=15
    volumes:
      - /game-data/mc-server:/data